-- This script was generated by the Schema Diff utility in pgAdmin 4. 
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated 
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps. 
 BEGIN;
 -- Type: account_status_enum

-- DROP TYPE IF EXISTS public.account_status_enum;

CREATE TYPE public.account_status_enum AS ENUM
    ('Incomplete', 'Complete');

ALTER TYPE public.account_status_enum
    OWNER TO supabase_admin;
    
 CREATE TABLE IF NOT EXISTS public.account
(
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    customer_id text COLLATE pg_catalog."default",
    supabase_id uuid,
    profile_url text COLLATE pg_catalog."default",
    status account_status_enum DEFAULT 'Incomplete'::account_status_enum,
    CONSTRAINT account_pkey PRIMARY KEY (id),
    CONSTRAINT account_supabase_id_key UNIQUE (supabase_id),
    CONSTRAINT account_user_id_key UNIQUE (customer_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.account
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.account
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.account TO anon;

GRANT ALL ON TABLE public.account TO authenticated;

GRANT ALL ON TABLE public.account TO postgres;

GRANT ALL ON TABLE public.account TO service_role;

GRANT ALL ON TABLE public.account TO supabase_admin;

 END;