export enum RoutePaths {
  Default = '/',
  Landing = '/landing',
  Signin = '/signin',
  Signup = '/signup',
  ForgotPassword = '/forgot-password',
  TermsOfService = '/terms-of-service',
  PrivacyPolicy = '/privacy-policy',
  ResetPassword = '/reset-password',
  User = '/user',
  GetStarted = '/user/get-started',
  Account = '/user/account',
  Apps = '/user/apps',
  Billing = '/user/billing',
  Admin = '/admin',
  AdminAccount = '/admin/account',
  AdminAccounts = '/admin/accounts',
  AdminApps = '/admin/apps',
}
