export enum RoutePaths {
  Default = '/',
  Home = '/home',
  Signin = '/signin',
  Signup = '/signup',
  ForgotPassword = '/forgot-password',
  TermsOfService = '/terms-of-service',
  PrivacyPolicy = '/privacy-policy',
  ResetPassword = '/reset-password',
  Store = '/store',
  StoreWithId = '/store/:id',
  Events = '/events',
  Notifications = '/notifications',
  Cart = '/cart',
  Account = '/account',
  AccountEvents = '/account/events',
  AccountOrderHistory = '/account/order-history',
  AccountAddresses = '/account/addresses',
  AccountEdit = '/account/edit',
  AccountSettings = '/account/settings',
}
