import LocalizedStrings from 'react-localization';

export const Strings = new LocalizedStrings({
    en: {
      signin: "Sign in",
      signup: "Sign up",
      callToAction: "Are you looking to build an app for your business?",
      subCallToAction: "Experience business to the leading-edge. Sign up to start your analysis.",
      status: "Status",
      development: "Development",
      emailConfirmation: "Email confirmation",
      emailConfirmationDescription: "Please check your email inbox to confirm your account",
      orContinueWith: "or continue with",
      emailAddress: "Email address",
      password: "Password",
      rememberMe: "Remember me",
      forgotYourPassword: "Forgot your password?",
      signIn: "Sign in",
      signInWith: "Sign in with",
      signUp: "Sign up",
      signUpWith: "Sign up with",
      doYouHaveAnAccount: "Do you have an account? Sign in",
      dontHaveAnAccount: "Don't have an account? Sign up",
      newPassword: "New password",
      updatePassword: "Update password",
      enterYourNewPassword: "Enter your new password",
      agreeToThe: "I agree to the",
      termsOfService: "Terms of Service",
      passwordReset: "Password reset",
      passwordResetDescription: "Please check your email inbox to reset your account",
      privacyPolicy: "Privacy Policy",
      yourEmailAddress: "Your email address",
      sendResetPasswordInstructions: "Send password reset",
      goBackToSignIn: "Go back to sign in",
      sendMagicLink: "Send magic link",
      signInWithPassword: "Sign in with password",
      emailErrorMessage: "You must provide a valid email address",
      passwordErrorMessage: "You must provide a valid password",
    }
});