import LocalizedStrings from 'react-localization';

export const Strings = new LocalizedStrings({
  en: {
    locale: 'English',
    signin: 'Sign in',
    signup: 'Sign up',
    callToAction: 'Are you looking to build an app?',
    subCallToAction:
      'Experience business to the leading-edge. Sign up to start your analysis.',
    status: 'Status',
    development: 'Development',
    emailConfirmation: 'Email confirmation',
    emailConfirmationDescription:
      'Please check your email inbox to confirm your account',
    orContinueWith: 'or continue with',
    emailAddress: 'Email address',
    password: 'Password',
    rememberMe: 'Remember me',
    forgotYourPassword: 'Forgot your password?',
    signIn: 'Sign in',
    signInWith: 'Sign in with',
    signUp: 'Sign up',
    signUpWith: 'Sign up with',
    doYouHaveAnAccount: 'Do you have an account? Sign in',
    dontHaveAnAccount: "Don't have an account? Sign up",
    newPassword: 'New password',
    updatePassword: 'Update password',
    enterYourNewPassword: 'Enter your new password',
    agreeToThe: 'I agree to the',
    termsOfService: 'Terms of Service',
    passwordReset: 'Password reset',
    passwordResetDescription:
      'Please check your email inbox to reset your account',
    passwordUpdated: 'Password updated',
    passwordUpdatedDescription: 'Your password has been successfully updated',
    privacyPolicy: 'Privacy Policy',
    yourEmailAddress: 'Your email address',
    sendResetPasswordInstructions: 'Send password reset',
    goBackToSignIn: 'Go back to sign in',
    sendMagicLink: 'Send magic link',
    signInWithPassword: 'Sign in with password',
    emailErrorMessage: 'You must provide a valid email address',
    passwordErrorMessage: 'You must provide a valid password',
    getStarted: 'Get started',
    getStartedSubtitle: 'Please send us a request with your business info',
    fieldEmptyError: 'This field cannot be empty',
    company: 'Company',
    companyPlaceholder: 'Company name',
    phoneNumber: 'Phone number',
    phoneNumberPlaceholder: '+1 (123) 456 7890',
    comment: 'Comment',
    commentPlaceholder: 'Describe who you are, your company and the idea',
    send: 'Send',
    thankyouForContacting: 'Thankyou for contacting!',
    thankyouForContactingSubtitle:
      'We will get back to you as soon as possible.',
    next: 'Next',
    account: 'Account',
    adminAccount: 'Admin Account',
    apps: 'Apps',
    adminApps: 'Admin Apps',
    billing: 'Billing',
    users: 'Users',
    adminUsers: 'Admin Users',
    deleteAccount: 'Delete Account',
    save: 'Save',
    profile: 'Profile',
    personalInformation: 'Personal Information',
    thisInfoWillBePublic: 'This information will be public',
    thisInfoWillBePrivate: 'This information will be private',
    location: 'Location',
    language: 'Language',
    delete: 'Delete',
    cancel: 'Cancel',
    deleteYourAccount: 'Delete your account?',
    deleteYourAccountDescription:
      'All the data associated to your user will be deleted.',
    requests: 'Requests',
    accepted: 'Accepted',
    updateRequests: 'Update Requests',
    updateAccepted: 'Update Accepted',
    requestedUserTitle: 'Accept request for',
    requestedUserDescription:
      'By accepting this request, you will be able to create an app for this user.',
    accept: 'Accept',
    createApp: 'Create App',
    requestUpdate: 'Request Update',
    editCoverPhoto: 'Edit Cover Photo',
    edit: 'Edit',
    appName: 'App name',
    addLink: 'Add Link',
    name: 'Name',
    link: 'Link',
    statusTypes: 'User Stories,Design,Development,Release',
    deleteApp: 'Delete this app?',
    deleteAppDescription: 'All data will be destroyed.',
  },
});
