// @generated by protoc-gen-es v0.3.0 with parameter "target=ts"
// @generated from file protobuf/common.proto (package common, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum common.StorageFolderType
 */
export enum StorageFolderType {
  /**
   * @generated from enum value: Avatars = 0;
   */
  Avatars = 0,

  /**
   * @generated from enum value: Thumbnails = 1;
   */
  Thumbnails = 1,
}
// Retrieve enum metadata with: proto3.getEnumType(StorageFolderType)
proto3.util.setEnumType(StorageFolderType, "common.StorageFolderType", [
  { no: 0, name: "Avatars" },
  { no: 1, name: "Thumbnails" },
]);

