-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.users
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone DEFAULT now(),
    supabase_id text COLLATE pg_catalog."default",
    company text COLLATE pg_catalog."default",
    email text COLLATE pg_catalog."default",
    phone_number text COLLATE pg_catalog."default",
    location json,
    language text COLLATE pg_catalog."default",
    request_status bigint,
    role bigint,
    apps json[],
    CONSTRAINT user_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

ALTER TABLE IF EXISTS public.users
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.users TO anon;

GRANT ALL ON TABLE public.users TO authenticated;

GRANT ALL ON TABLE public.users TO postgres;

GRANT ALL ON TABLE public.users TO service_role;

CREATE TABLE IF NOT EXISTS public.apps
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    created_at timestamp with time zone DEFAULT now(),
    name text COLLATE pg_catalog."default",
    status bigint,
    updated_at timestamp with time zone,
    products text[] COLLATE pg_catalog."default",
    images json[],
    links json[],
    CONSTRAINT apps_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.apps
    OWNER to postgres;

ALTER TABLE IF EXISTS public.apps
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.apps TO anon;

GRANT ALL ON TABLE public.apps TO authenticated;

GRANT ALL ON TABLE public.apps TO postgres;

GRANT ALL ON TABLE public.apps TO service_role;
